### ISSUE TITLE
Expose the actual tree object for the instance

### ISSUE THREAD

**Issue by arjunmehta** [lyndseybrowning/trie-prefix#3]
It would be great to have access to the actual tree produced
So in addition to `myTree.dump()`, something like `myTrie.tree()`:

```javascript
/**
 * Get a the generated trie-tree
*/
tree() {
  return trie;
},
```

This is useful in cases where there are large trees. I needed to crawl the tree, and the only way I could otherwise do that with this library would be to stringify then parse. However, that has memory implications.

Thoughts? I can create a pull request.

**Comment by lyndseybrowning** [comment]
Hi arjunmehta,

I'm happy for you to create a pull request 👍 

All done. Thanks :)
